version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel-nginx
    ports:
      - "80:80"           # App en http://localhost
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: laravel-phpmyadmin
    ports:
      - "8080:80"         # phpMyAdmin en http://localhost:8080
    environment:
      - PMA_HOST=db
      - PMA_USER=laravel
      - PMA_PASSWORD=laravel
    depends_on:
      - db

volumes:
  mysql_data:
